# Site settings
title: mtl dev
email: damacisaac@gmail.com
description: Tips for building beautiful web applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://damacisaac.github.io" # the base hostname & protocol for your site
# twitter_username: dmacis
github_username:  damacisaac

# Build settings
markdown: kramdown

comments:
    provider: disqus
    disqus:
        short_name: mtldev

analytics:
  provider: google
  google:
      tracking_id : 'UA-63556868-1'
